server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://oeadfpfbqsyndc:5c2a87449ce68e4d03bbbfd6d8f985870c3e25e3139f92501532067f1b820fa8@ec2-23-23-128-222.compute-1.amazonaws.com:5432/d97an27ild2jdo
    username: oeadfpfbqsyndc
    password: 5c2a87449ce68e4d03bbbfd6d8f985870c3e25e3139f92501532067f1b820fa8
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend

